---
- name: Copia instalador y dependencias para JohnTheRipper con GPU
  hosts: fisicos
  tasks:
    - name: Instala paquetes requeridos por los instructores
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nvidia-cuda-toolkit
        - libssl-dev
        - ccache
        - git
        - build-essential
      become: yes
    - git:
        dest: "{{ ansible_user }}/JohnTheRipper"
        repo: https://github.com/magnumripper/JohnTheRipper.git
