---
- name: Instala la máquina virtual de para laboratorio de heartbleed
  hosts: fisicos
  tasks:
    - name: Plantilla de jinja para XML de VM de Kali
      template:
        src: ../files/heartbleed.xml.j2
        dest: /tmp/heartbleed.xml
        mode: 0644
        owner: root
        group: root
      become: yes
    - name: Importa archivo XML para VM de Kali
      command: virsh define /tmp/heartbleed.xml
      become: yes
    - name: Mueve imagen de heartbleed a directorio de imagenes
      get_url:
        url: http://10.42.30.5/vms/heartbleed.qcow2
        dest: /var/lib/libvirt/images/heartbleed.qcow2
        mode: 0775
        owner: "{{ ansible_user }}"
