dist: xenial

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qy lxc libvirt-daemon-system python3-pip wireshark-common apache2
  - sudo mkdir /var/www/html/vms/
  - sudo touch /var/www/html/vms/{NagiosCore.qcow2.bz2,CentOS.qcow2.bz2,kali.qcow2.bz2,kali-{1..3}.qcow2.bz2,firefox-58.0a1.en-US.linux-x86_64.tar.bz2,rootkit.qcow2.bz2,heartbleed.qcow2.bz2,ubuntu16.04-02.qcow2.bz2,FreePBX.qcow2.bz2}
  - sudo pip install ansible
  - sudo groupadd wireshark
  - sudo apt-get purge mysql-server*
  - mkdir -p ~/.jupyter/ ~/Arduino/libraries/IBM_LMIC_framework/src/lmic/
  - touch ~/.jupyter/jupyter_notebook_config.py ~/Arduino/libraries/IBM_LMIC_framework/src/lmic/config.h

script:
  - "ansible-playbook -i inventory/hosts.example --syntax-check cursos/*yml cursos/*/*yml cursos/*/*/*yml"
  - "ansible-playbook -i inventory/hosts.example  cursos/01-upgrade.yml"
  - sudo apt-get -qy install nodejs
  - "ansible-playbook -i inventory/hosts.example -C cursos/*yml cursos/*/*yml cursos/*/*/*yml"
  - "echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections"
  - "echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections"
