dist: trusty

before_install:
  - sudo apt-get -qq update

install:
  - sudo pip install ansible

script:
  - "ansible-playbook -i inventory/hosts.example --syntax-check servidores/*yml"
  - "sudo ansible-playbook -i inventory/hosts.example --syntax-check servidores/01-upgrade.yml"
  - "sudo ansible-playbook -i inventory/hosts.example --syntax-check servidores/02-base_setup.yml"
