---
- name: Configura servicios a monitorear
  hosts: fisicos
  tasks:
    - name: Plantilla de jinja para archivo interfaces
      template:
        src: files/kali.xml.j2
        dest: /tmp/kali.xml
        mode: 0644
        owner: root
        group: root
      become: yes

