---
- name: Configura servicios a monitorear
  hosts: srv
  tasks:
    - name: Copia agente NRPE
      unarchive:
        dest: /home/greencore/
        src: https://assets.nagios.com/downloads/nagiosxi/agents/linux-nrpe-agent.tar.gz
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
        remote_src: yes
      become: yes

