---
- name: Preinstala Nagiox XI
  hosts: nagiosxi
  tasks:
    - name: Copia instalador de nagiosxi
      unarchive:
        dest: /home/greencore/ 
        src: https://assets.nagios.com/downloads/nagiosxi/5/xi-5.4.2.tar.gz
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        remote_src: yes
      become: yes
    - name: Crea configuración base para todos los contenedores
      command: lxc-attach -n {{ item[0] }} -- {{ item[1] }}
      with_nested:
        - [ 'nagiosxi', 'servicios1', 'servicios2']
        - [ 'yum update -y', 'yum install openssh-server -y', 'systemctl enable sshd', 'systemctl start sshd', 'useradd -s /bin/bash -G wheel -m -p "$6$dF3C39/G$6oRDu6OCq9Td2hU1iN4lRyMTIPtTkq3bIivTAEqxUGOH6LRAkmkGcqjlLN4jT6S1buHEUmCJAqIhqnPcMKbxE1" greencore']
      become: yes
