---
- name: Prepara los clientes para agregarlos al Directorio Activo
  hosts: fisicos
  tasks:
  - name: Usa debconf para responde las preguntas que haría APT
    debconf:
      name: krb5-config
      question: krb5-config/default_realm
      value: greencore.local
      vtype: string
    become: yes
  - name: Instala paquetes requeridos para esta receta
    apt: 
      name: "{{ item }}"
      state: installed
    with_items:
      - paquete1
      - ...
    become: yes
  - name: Configuración de interfaces
    copy:
      src: files/interfaces
      dest: /etc/network/interfaces
      mode: 0644
      owner: root
      group: root
    become: yes
#
#
#
#
## Extra: Biosdevname   
  - name: Deshabilita biosdevname
    lineinfile:
      regexp: '^GRUB_CMDLINE_LINUX=""'
      dest: "/etc/default/grub"
      line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
      state: present
      backrefs: yes
    become: yes
    register: grub_default_biosdevname
  - name: Actualiza grub luego de deshabilitar biosdevname
    command: grub-mkconfig -o /boot/grub/grub.cfg
    ignore_errors: true
    become: yes
    when: grub_default_biosdevname.changed
