---
- name: Instala la máquina virtual de Kali
  hosts: fisicos
  strategy: free
  tasks:
    - name: Instala paquetes requeridos por los instructores
      apt:
        name: pbzip2
        state: present
      become: yes
    - name: Plantilla de jinja para XML de VM de Kali
      template:
        src: files/kalinv.xml.j2
        dest: /tmp/kalinv.xml
        mode: 0644
        owner: root
        group: root
      become: yes
    - name: Importa archivo XML para VM de Kali
      command: virsh define /tmp/kalinv.xml
      become: yes
