---
- name: Instala la base para los equipos de los laboratorios de Greencore Solutions
  hosts: fisicos
  tasks:
  - name: Deshabilita biosdevname
    lineinfile:
      regexp: '^GRUB_CMDLINE_LINUX=""'
      dest: "/etc/default/grub"
      line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
      state: present
      backrefs: yes
    become: yes
    register: grub_default_biosdevname
  - name: Actualiza grub luego de deshabilitar biosdevname
    command: grub-mkconfig -o /boot/grub/grub.cfg
    ignore_errors: true
    become: yes
    when: grub_default_biosdevname.changed
  - name: Configura Chromium Browser en modo Incognito
    lineinfile:
      regexp: '^CHROMIUM_FLAGS=""'
      dest: "/etc/chromium-browser/default"
      line: 'CHROMIUM_FLAGS="-incognito"'
      state: present
      backrefs: yes
    become: yes
  - name: Interfaces con bridge br0
    copy:
      dest: /etc/network/interfaces
      src: ../files/interfaces-bridge
      mode: 0644
      owner: root
      group: root
    become: yes
  - name: Instala tarea programada para apagado automático de equipos
    copy:
      dest: /etc/cron.d/shutdown
      src: ../files/cron-shutdown
      mode: 0644
      owner: root
      group: root
    become: yes
  - name: Instala script turn-on.sh como interface de wakeonlan
    copy:
      dest: /usr/local/bin/turn-on.sh
      src: ../files/turn-on.sh
      mode: 0755
      owner: root
      group: root
    become: yes
  - name: Fog DHCP Hostname en dhclient hooks
    copy:
      dest: /etc/dhcp/dhclient-enter-hooks.d/unset_old_hostname
      content: "unset old_host_name"
      mode: 0644
      owner: root
      group: root
    become: yes
  - name: Fog DHCP Hostname en /etc/hostname
    copy:
      dest: /etc/hostname
      content: ""
      mode: 0644
      owner: root
      group: root
    become: yes
    ignore_errors: true
  - user:
      name: greencore
      shell: /bin/bash
      groups: sudo,dialout,libvirt,adm
      append: yes
    become: yes
