---
- name: Instala la base para los equipos de los laboratorios de Greencore Solutions
  hosts: fisicos
  strategy: free
  tasks:
  - name: Remueve paqute deja-dup
    apt:
      name: "{{ item }}"
      state: absent
    become: yes
    with_items:
      - modemmanager
      - deja-dup
      - aptdaemon
      - update-manager-core
  - name: Instala módulos de python con pip3
    pip:
      name: "{{ item }}"
      state: latest
      executable: pip3
    with_items:
      - asciinema
      - ansible
    become: yes
  - name: Agregamos llave de GPG para Visual Code
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
      keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    become: yes
  - name: Crea archivo de fuentes para paquetes de Visual Code
    copy:
      dest: /etc/apt/sources.list.d/vscode.list
      content: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      owner: root
      group: root
    become: yes
  - name: Actualiza cache
    apt:
      update_cache: yes
    become: yes
  - name: Usa debconf para decirle a wireshark que permita escucha a usuarios no-root
    debconf:
      name: wireshark-common
      question: wireshark-common/install-setuid
      value: true
      vtype: boolean
    become: yes
  - name: Instala paquetes requeridos por los instructores
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - virt-manager
      - virtualbox
      - fritzing
      - bridge-utils
      - qemu-kvm
      - qemu-system
      - libvirt-bin
      - ubuntu-vm-builder
      - pwgen
      - gnome-shell
      - gnome-tweak-tool
      - chromium-browser
      - screen
      - byobu
      - openssh-server
      - dia
      - shutter
      - vlc
      - mpv
      - wakeonlan
      - git
      - python3-pip
      - avahi-discover
      - udpcast
      - pv
      - docker-compose
      - code
      - nmap
      - wireshark
      - etherape
      - iftop
      - pbzip2
    become: yes
  - name: Agrega a usuario ansible_user en grupos necesarios
    user:
      name: "{{ ansible_user }}"
      groups: wireshark,sudo,docker,dialout,libvirt
      append: yes
    become: yes
