---
- name: Instala la base para los equipos de los laboratorios de Greencore Solutions
  hosts: fisicos
  strategy: free
  tasks:
  - name: Remueve paquetes en conflicto con los laboratorios
    apt:
      name: "{{ item }}"
      state: absent
    become: yes
    with_items:
      - modemmanager
      - deja-dup
      - aptdaemon
      - update-manager-core
      - unattended-upgrades
      - docker
      - docker-engine
      - docker.io
  - name: Usa debconf para decirle a wireshark que permita escucha a usuarios no-root
    debconf:
      name: wireshark-common
      question: wireshark-common/install-setuid
      value: true
      vtype: boolean
    become: yes
  - name: Instala paquetes requeridos por los instructores
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - virt-manager
      - virtualbox
      - fritzing
      - bridge-utils
      - qemu-kvm
      - qemu-system
      - libvirt-bin
      - ubuntu-vm-builder
      - pwgen
      - gnome-shell
      - gnome-tweak-tool
      - chromium-browser
      - screen
      - byobu
      - openssh-server
      - dia
      - shutter
      - vlc
      - mpv
      - wakeonlan
      - git
      - python3-pip
      - avahi-discover
      - udpcast
      - pv
      - docker-compose
      - code
      - nmap
      - wireshark
      - etherape
      - iftop
      - pbzip2
      - distcc
      - distcc-pump
      - distccmon-gnome  
      - ccache
      - bison
      - flex
      - libncurses-dev
      - libelf-dev
      - libssl-dev
      - rtl-sdr
      - gqrx-sdr
      - nodejs
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
    become: yes
  - name: Instala paquete de Atom usando ATP
    apt:
      deb: https://github.com/atom/atom/releases/download/v1.29.0/atom-amd64.deb
      state: present
    become: yes
  - name: Instala m贸dulos de python con pip3
    pip:
      name: "{{ item }}"
      state: latest
      executable: pip3
    with_items:
      - asciinema
      - mu-editor
      - ansible
      - apio
    become: yes
  - name: Instala m贸dulos de python con pip
    pip:
      name: "{{ item }}"
      state: latest
    with_items:
      - platformio
        #    become: yes
  - name: Agrega a usuario ansible_user en grupos necesarios
    user:
      name: "{{ ansible_user }}"
      #      groups: wireshark,sudo,docker,dialout,libvirt
      groups: wireshark,sudo,docker,dialout
      append: yes
    become: yes
  - name: Crea archivo de configuraci贸n de Distcc
    copy:
      dest: /etc/default/distcc
      src: files/default-distcc
      owner: root
      group: root
      mode: 0644
    become: yes
  - name: Crea configuraci贸n de hosts para distcc
    copy:
      dest: /etc/distcc/hosts
      src: files/distcc-hosts
      owner: root
      group: root
      mode: 0644
    become: yes
  - name: Instala paquetes de npm
    npm:
      name: "{{ item }}"
      global: yes
    with_items:
      - node-red
#      - terminalizer
    become: yes
