---
- name: Instala la base para los equipos de los laboratorios de Greencore Solutions
  hosts: all
  tasks:
  - name: Cambia cr.archive por ubuntu-mirror
    replace: >
      regexp="deb http:\/\/cr.archive.ubuntu.com"
      replace="deb http://ubuntu-mirror.greencore.int"
      dest=/etc/apt/sources.list
    become: yes
  - name: Elimina lineas que referencien a backports
    lineinfile: >
      regexp="-backports"
      dest=/etc/apt/sources.list
      state=absent
    become: yes
  - name: Instala aptitude (requerido por ansible)
    apt:
      name: aptitude
      state: latest
      update_cache: yes
    become: yes
  - name: Actualiza cache, paquetes, y autoremueve
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
    become: yes
  - name: Remueve paqute deja-dup
    apt:
      name: "{{ item }}"
      state: absent
    become: yes
    with_items:
      - modem_manager
      - deja-dup
  - name: Instala paquetes requeridos por los instructores
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - virt-manager
      - virtualbox
      - fritzing
      - bridge-utils
      - qemu-kvm
      - qemu-system
      - libvirt-bin
      - ubuntu-vm-builder
      - pwgen
      - gnome-shell
      - gnome-tweak-tool
      - chromium-browser
      - screen
      - byobu
      - openssh-server
      - dia
      - shutter
  - name: Deshabilita biosdevname
    lineinfile:
      regexp: '^GRUB_CMDLINE_LINUX=""'
      dest: "/etc/default/grub"
      line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
      state: present
      backrefs: yes
    become: yes
    register: grub_default_biosdevname
  - name: Actualiza grub luego de deshabilitar biosdevname
    #command: update-grub
    command: grub-mkconfig -o /boot/grub/grub.cfg
    ignore_errors: true
    become: yes
    when: grub_default_biosdevname.changed
  - name: Configura Chromium Browser en modo Incognito
    lineinfile:
      regexp: '^CHROMIUM_FLAGS=""'
      dest: "/etc/chromium-browser/default"
      line: 'CHROMIUM_FLAGS="-incognito"'
      state: present
      backrefs: yes
    become: yes
  - name: Interfaces con bridge br0
    copy:
      dest: /etc/network/interfaces
      src: ../files/interfaces-bridge
      mode: 0644
      owner: root
      group: root
    become: yes
  - name: Instala tarea programada para apagado automático de equipos
    copy:
      dest: /etc/cron.d/shutdown
      src: ../files/cron-shutdown
      mode: 0644
      owner: root
      group: root
    become: yes
  - name: Instala script turn-on.sh como interface de wakeonlan
    copy:
      dest: /usr/local/bin/turn-on.sh
      src: ../files/turn-on.sh
      mode: 0755
      owner: root
      group: root
    become: yes
  - name: Fog DHCP Hostname en dhclient hooks
    copy:
      dest: /etc/dhcp/dhclient-enter-hooks.d/unset_old_hostname
      content: "unset old_host_name"
      mode: 0644
      owner: root
      group: root
    become: yes
  - name: Fog DHCP Hostname en /etc/hostname
    copy:
      dest: /etc/hostname
      src: /dev/null
      mode: 0644
      owner: root
      group: root
    become: yes
