---
- name: Instala laboratorio para clases de nagios
  hosts: fisicos
  tasks:
    - name: Instala pip3
      apt:
        name: python3-pip
        state: installed
      become: yes
    - name: Instala esptool con pip
      pip:
        name: esptool 
        state: present
        executable: pip3
      become: yes
    - name: Instala ampy con pip
      pip:
        name: adafruit-ampy 
        state: present
        executable: pip3
      become: yes
    - name: Descarga circuitplayground para ESP8266 Feather
      get_url:
        url: https://github-cloud.s3.amazonaws.com/releases/66166069/705523e8-1341-11e7-87ba-571d08cc1547.bin?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAISTNZFOVBIJMK3TQ%2F20170331%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170331T012804Z&X-Amz-Expires=300&X-Amz-Signature=7d70a5a72135fb2a3e82a4059fe621dd8249691c5256b986f679fd40135199ae&X-Amz-SignedHeaders=host&actor_id=20340677&response-content-disposition=attachment%3B%20filename%3Dadafruit-circuitpython-feather_huzzah-0.9.3.bin&response-content-type=application%2Foctet-stream
        dest: /home/greencore
