---
- name: Instala laboratorio para clases de nagios
  hosts: fisicos
  tasks:
    - name: Instala paquetes requeridos
      apt: 
        name: "{{ item }}"
        state: installed
      with_items:
        - gqrx
        - gpredict
        - python-pip
      become: yes
    - name: Copia instalador viejo de nagiosx
      get_url:
        dest: /home/greencore/
        src: http://128.52.184.65/appinventor2-setup_2.3_all.deb
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        remote_src: yes
    - name: Instala dependencias de python para módulo de ansible de LXC
      pip: name=lxc-python2 state=present
      become: yes
    - name: Configura defaults de LXC
      lineinfile:
        regexp: "^lxc.network.link = lxcbr0"
        dest: "/etc/lxc/default.conf"
        line: "lxc.network.link = br0"
        state: present
        backrefs: yes
      become: yes
    - name: Crea directorio para cliente de SSH
      file:
        path: "{{ ansible_env.HOME }}/.ssh/"
        state: directory
        mode: 0755
        owner: greencore
        group: greencore
    - name: Configura cliente de SSH
      copy:
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        content: |
                Host 10.42.25.*
                  StrictHostKeyChecking no
                  UserKnownHostsFile=/dev/null
        owner: greencore
        group: greencore
